backend/app/auth/apple_auth_controller.go
backend/app/auth/apple_auth_service.go
backend/app/user/user_controller.go
backend/cmd/jwt_generator/jwt_generator.go
backend/go.mod
backend/go.sum
backend/main.go

1. 애플로그인 토큰 validate 작성
2. 토큰 generator 작성
3. Makefile swag init 이슈 수정

feat(apple-login) : 애플로그인 토큰 validate 작성, 토큰 generator 작성

---

backend/app/auth/apple_auth_controller.go
backend/app/auth/auth_controller.go
backend/app/common/common_controller.go
backend/app/user/user_controller.go
backend/main.go
backend/pkg/routes/public_routes.go
backend/pkg/routes/swagger_routes.go

1. 문서에서 api prefix 제거
2. 구글 api 문서화
3. /docs 접근 시 문서로 리다이렉트
4. title 및 description 변경
5. 없는 api 문서 삭제

JOO-31 feat(swagger) : swagger desc 변경, 리다이렉트, basic path 설정

---

backend/app/auth/apple_handler.go
backend/app/auth/apple_model.go
backend/app/auth/apple_usecase.go
backend/app/user/user_handler.go
backend/main.go
backend/pkg/middleware/apple_auth.go
backend/pkg/routes/private_routes.go
backend/pkg/routes/public_routes.go
backend/pkg/util/apple_public_key_loader.go

1. verify api 와 토큰발급 api 를 합침
2. 토큰발급 api 작성 및 문서화
3. 애플 jwt 미들웨어 작성

Feature/hyunjun/joo 13 apple 토큰발급 api, jwt middleware 작성 

---

backend/app/auth/auth_usecase.go
backend/app/auth/google_handler.go
backend/app/tag/tag_handler.go
backend/app/tag/tag_model.go
backend/app/tag/tag_usecase.go
backend/app/user/user_handler.go
backend/app/user/user_model.go
backend/app/user/user_usecase.go
backend/pkg/middleware/apple_auth.go
backend/pkg/middleware/user_mid.go
backend/pkg/routes/private_routes.go

- 데이터 셋과 거의 상관 없는 Tag 부분 만들었습니다.
JWT 사용하는 것 완성해 두었는데, 제가 생각한 로직은 다음과 같습니다.
Client 에서 google 인증 -> Client 에서 accessToken( google ) 을 건내줌 -> Server 에서 accessToken( google )을 확인 함 -> 확인하고 email 이 가입되어 있는지를 체크 -> 없으면 accessToken ( joosum ) , refreshToken ( joosum ) 을 빈 값 으로 주고 회원 가입으로 넘어감 or 있으면 accessToken ( joosum ), refreshToken ( joosum ) 을 header 의 Authorization 에 넣고 통신을 주고 받음.
어떠신지 의견 남겨주시면, 통일해서 마무리 되었으면 좋겠네요.

Tag API 와 JWT 사용

---

backend/app/auth/apple_handler.go
backend/app/auth/auth_handler.go
backend/app/auth/auth_model.go
backend/app/auth/auth_usecase.go
backend/app/tag/tag_handler.go
backend/cmd/jwt_generator/jwt_generator.go
backend/pkg/middleware/user_mid.go
backend/pkg/util/http_error.go
backend/pkg/util/jwt_generator.go

1. 스네이크 -> 카멜 케이스
2. JWT 헤더에 kid 제거
3. 엔드포인트 tag 복수로 변경
4. usecase 오탈자 수정
5. 미들웨어 jwt prefix 이슈 수정
6. 애플토큰이면 email 을 토큰에서 꺼내도록 수정

NO-JIRA feat(login) :  애플토큰이면 email 을 토큰에서 꺼내도록 수정

---

backend/app/auth/apple_handler.go
backend/app/auth/auth_handler.go
backend/app/auth/google_handler.go
backend/app/tag/tag_handler.go
backend/main.go
backend/pkg/middleware/user_mid.go

1. 미들웨어에서 가입된 이메일 못찾았을 때 404 로 수정
2. swagger 에서 토큰 헤더에 담아 요청보낼 수 있도록 수정
3. 회원가입 안했을 때 http method 401 -> 200
4. GetUserByEmail 예외처리
5. 스웨거 배포날짜 명시하도록 수정

http method 수정, swagger 설정, 예외처리 등 

---

backend/app/auth/apple_handler.go
backend/app/auth/auth_handler.go
backend/app/auth/google_handler.go
backend/app/tag/tag_handler.go
backend/main.go
backend/pkg/middleware/user_mid.go
backend/pkg/routes/private_routes.go

1. 미들웨어에서 가입된 이메일 못찾았을 때 404 로 수정
2. swagger 에서 토큰 헤더에 담아 요청보낼 수 있도록 수정
3. 회원가입 안했을 때 http method 401 -> 200
4. GetUserByEmail 예외처리
5. 스웨거 배포날짜 명시하도록 수정

http method 수정, swagger 설정, 예외처리 등

---

backend/app/link/link_handler.go
backend/app/link/link_model.go
backend/app/link/link_usecase.go
backend/app/link/linkbook_handler.go
backend/app/link/linkbook_model.go
backend/app/link/linkbook_usecase.go
backend/pkg/routes/private_routes.go

기본적인 CURD 랑 조금 더 구현해 보았습니다.
link 라는 자료구조가 있어서 linkBook들은 link 로 변경하였습니다.

link CURD 구현

---

.github/workflows/deploy.yml

참고한 링크 공유드립니당~~
블로그: https://supreme-ys.tistory.com/m/161?category=951565
ssh Github action 라이브러리 (?) 문서: https://github.com/appleboy/ssh-action

CI/CD 파이프라인 이슈 수정 

---

backend/app/link/linkbook_handler.go
backend/app/link/linkbook_model.go
backend/app/link/linkbook_usecase.go
backend/go.mod
backend/pkg/db/collection.go
backend/pkg/routes/private_routes.go

to do 
- 총 링크 갯수 및 기본폴더 링크 갯수 추가
- 각 폴더 총 링크 갯수 추가 
> 링크 api develop 에 1차로 머지되면 링크 더미데이터 생성해서 추가해야 할 것 같아요 
폴더 지정해서 링크 등록 시 링크북 컬렉션에 
last_saved_at 에 time.Now() 로 업데이트 필요해요 
링크북, 링크 둘다 develop 에 1차로 머지하고 계속 작업해요~~

링크북 등록, 목록 api 작성 

---

backend/app/auth/auth_handler.go
backend/app/user/user_model.go
backend/app/user/user_usecase.go

현재 로그인 된 회원의 정보를 반환

---

backend/app/auth/auth_handler.go

- User 불러오는게 잘 못 되어 있어서 수정햇습니다.

swagger 에러 수정

---

backend/app/auth/auth_handler.go
backend/app/auth/auth_model.go
backend/app/auth/auth_usecase.go

accessToken idToken 으로 통일했습니다.

accessToken 을 idToken 으로 변경

---

backend/app/link/link_model.go
backend/app/link/linkbook_handler.go
backend/app/link/linkbook_model.go
backend/app/link/linkbook_usecase.go
backend/pkg/db/model.go
backend/pkg/routes/private_routes.go

1. 링크북 수정 api 작성
2. 링크북 등록/수정 시 누락된 카멜케이스 수정
3. 링크북 목록에 count 코드 임시작성

JOO-77 feat(link-book) : 링크북 수정 api 작성, 링크북 등록/수정 시 누락된 카멜케이스 수정

---

backend/app/auth/auth_handler.go
backend/app/link/link_handler.go
backend/app/link/link_model.go
backend/app/link/link_usecase.go
backend/app/link/linkbook_handler.go
backend/app/link/linkbook_usecase.go
backend/app/page/page_handler.go
backend/app/tag/tag_handler.go
backend/pkg/db/collection.go
backend/pkg/middleware/user_mid.go
backend/pkg/routes/private_routes.go
backend/pkg/util/db_loader.go

- link api 가 제대로 동작 안하던게 많더라구요 ㅠ 수정했습니다.
- main page 용 api 만들었습니다.
- middleware 에서 user id 라고 사용하는데, user 정보로 변경하고 사용법을 통일했습니다.

main page, middleware 수정, link api 점검

---

backend/app/link/link_model.go
backend/app/link/link_usecase.go
backend/app/link/linkbook_handler.go
backend/app/link/linkbook_model.go
backend/app/link/linkbook_usecase.go
backend/pkg/db/model.go
backend/pkg/routes/private_routes.go

삭제된 링크 갯수를 반환하기 위해 링크삭제 response 를 살짝 바꿨어요~
error -> (*mongo.DeleteResult, error)

JOO-77 feat(link-book) : 링크북 삭제 api 작성

---

backend/app/link/link_model.go
backend/app/link/link_usecase.go
backend/app/link/linkbook_model.go

- link 생성, 수정 시에 linkBookName 업데이트합니다.

link에 linkBook데이터 추가

---

backend/app/link/linkbook_handler.go
backend/app/link/linkbook_model.go
backend/go.mod
backend/go.sum
backend/main.go
backend/pkg/util/validator.go

star 수 제일 많은 request validator 가져왔어요~
메뉴얼: https://github.com/go-playground/validator
샘플코드: https://github.com/go-playground/validator/blob/master/_examples/simple/main.go

JOO-88 feat(validator) : validator 설정 및 샘플코드 추가

---

backend/app/link/link_handler.go
backend/app/link/link_model.go
backend/app/link/link_usecase.go
backend/app/link/linkbook_handler.go
backend/app/link/linkbook_model.go
backend/go.mod
backend/go.sum
backend/main.go
backend/pkg/util/validator.go

- 링크 sort 추가
- 링크 title 로 검색 추가

링크 sort, 링크 title 기반 검색 추가

---

backend/app-back.code-workspace
backend/app/link/link_handler.go
backend/app/link/link_model.go
backend/app/link/link_usecase.go
backend/pkg/routes/private_routes.go

- links 버그 수정
- link book 기반으로 가져오는거 라우터 이동
- link book 기반으로 가져오는거 sort, search 추가
- swagger 수정

link book 관련 수정

---

backend/app/link/link_handler.go
backend/app/link/link_model.go
backend/app/link/link_usecase.go

sort order 추가

---

backend/app/link/linkbook_model.go
backend/app/link/linkbook_usecase.go

1. total link count 안넘어가는 이슈 수정
2. 기본 링크북 처음으로 정렬
3. 기본링크북 폴더색상 변경

JOO-77 feat(link-book) : 링크북 피드백 반영

---

backend/app/auth/auth_model.go
backend/app/user/user_model.go

age의 int 크기 수정

---

backend/app/tag/tag_handler.go
backend/app/tag/tag_model.go
backend/app/tag/tag_usecase.go
backend/pkg/db/collection.go
backend/pkg/routes/private_routes.go
backend/pkg/util/db_loader.go

db 에 태그를 스트링 리스트로 저장하도록 수정했어요. 
api 하나로 upsert 로 동작하도록 했어요. 
조회, 등록만 건드렸어요.

JOO-55 feat(tag) : 조회 및 등록 api 작성

---

backend/app/auth/apple_handler.go
backend/app/auth/auth_handler.go
backend/app/auth/auth_usecase.go
backend/app/auth/google_handler.go
backend/cmd/jwt_generator/jwt_generator.go
backend/pkg/util/jwt_generator.go

1. JWT 토큰의 권한이 USER 만 담기도록 수정
2. 권한: boolean -> 리스트로 수정

JOO-98 feat(roles) : JWT 토큰의 권한이 USER 만 담기도록 수정

---

backend/app/link/link_handler.go
backend/app/link/link_model.go
backend/app/link/link_usecase.go

1. 다중 링크 삭제 api 로 수정
2. deletedCount 반환하도록 수정

JOO-100 feat(delete-links) : 다중 링크 삭제 api 로 수정

---

backend/app/link/link_usecase.go

- 일부 썸네일 안되는 경우 에러처리 추가
- 짧아서 머지 시키겠습니다.

썸네일 버그 핫픽스 

---

backend/app/auth/naver_handler.go
backend/app/auth/naver_model.go
backend/app/auth/naver_usecase.go

로직 자체는 이전 google, apple 보다 쉽네요.
근데 너무 로그인 관련 코드랑 파일이 많아져서 나누고 싶네요.

naver 로그인 

---

backend/pkg/routes/public_routes.go

route added
